#! /bin/sh

sxhkd &
feh --bg-fill /home/nickrot/Pictures/wallpapers/tripmount.jpg &
compton --config /home/nickrot/.config/compton/compton.conf &
polybar main &
xbindkeys &

bspc monitor -d 0000 0001 0010 0011 0100 0101 0110 0111

bspc config border_width         1
bspc config window_gap          0

#bspc config top_padding		16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#5fafa5'
